name: Java CI to create and upload release on pull request
on:
  push:
    tags:
      - '*'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: use github.workspace as working dir
        run: cd ${{ github.workspace }}
      - name: compile
        run: javac -cp ./ -d ./ ./personal/yhchoi/java/lib/java_class_parser/*.java ./personal/yhchoi/java/lib/java_class_parser/attributes/*.java ./personal/yhchoi/java/lib/java_class_parser/constants/*.java ./personal/yhchoi/java/lib/java_class_parser/members/*.java
      - name: build_binary_jar
        run: jar -c -f java_class_parser_${{ github.ref_name }}_java21_bin.jar ./personal/yhchoi/java/lib/java_class_parser/*.class ./personal/yhchoi/java/lib/java_class_parser/attributes/*.class ./personal/yhchoi/java/lib/java_class_parser/constants/*.class ./personal/yhchoi/java/lib/java_class_parser/members/*.class
      - name: build_source_jar
        run: jar -c -f java_class_parser_${{ github.ref_name }}_java21_src.jar ./personal/yhchoi/java/lib/java_class_parser/*.class ./personal/yhchoi/java/lib/java_class_parser/attributes/*.class ./personal/yhchoi/java/lib/java_class_parser/constants/*.class ./personal/yhchoi/java/lib/java_class_parser/members/*.class ./personal/yhchoi/java/lib/java_class_parser/*.java ./personal/yhchoi/java/lib/java_class_parser/attributes/*.java ./personal/yhchoi/java/lib/java_class_parser/constants/*.java ./personal/yhchoi/java/lib/java_class_parser/members/*.java
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./*.jar
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          title: "Version ${{ github.ref_name }}"
          prerelease: false
          files: |
            ./LICENSE.txt
            ./*.jar
