name: Java CI to create and upload release on pull request
on:
  # workflow_dispatch:
  push:
    tags:
      - '*'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    strategy:
      matrix:
        java_vers: [21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java_vers }}'
          distribution: 'temurin'
      - name: make dir
        run: mkdir compiled_${{ matrix.java_vers }}
      - name: compile
        run: javac -cp ${{ github.workspace }} --release ${{ matrix.java_vers }} -d ./compiled_${{ matrix.java_vers }}/ ${{ github.workspace }}/**/*.java
      - name: build_binary_jar
        run: jar -c -f ./jar/java_class_parser_${{ github.ref_name }}_java${{ matrix.java_vers }}_bin.jar ./compiled_${{ matrix.java_vers }}/**/*.class
      - name: build_source_jar
        run: jar -c -f ./jar/java_class_parser_${{ github.ref_name }}_java${{ matrix.java_vers }}_src.jar ./compiled_${{ matrix.java_vers }}/**/*.class ${{ github.workspace }}/**/*.java
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./jar/*
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          title: "Version ${{ github.ref_name }}"
          prerelease: false
          files: |
            ${{ github.workspace }}/LICENSE.txt
            ./jar/*.jar
