name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: compile
        run: javac -cp ${{ github.workspace }} -d ./compiled/ --release 21 ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/attributes/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/constants/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/members/*.java
      - name: build_binary_jar
        run: jar -c -f ./jar/java_class_parser_${{ env.build-number }}_binary.jar ./compiled/personal/yhchoi/java/lib/java_class_parser/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/attributes/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/constants/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/members/*.class
      - name: build_source_jar
        run: jar -c -f ./jar/java_class_parser_${{ env.build-number }}_source.jar ./compiled/personal/yhchoi/java/lib/java_class_parser/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/attributes/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/constants/*.class ./compiled/personal/yhchoi/java/lib/java_class_parser/members/*.class ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/attributes/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/constants/*.java ${{ github.workspace }}/personal/yhchoi/java/lib/java_class_parser/members/*.java
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./jar/*
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: ./jar/*.jar
